[package]
name = "rip"
version = "0.3.0"
edition = "2021"
authors = ["Kasyanov Nikolay Alexeyevich (Unbewohnte)"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
